openzipkin/zipkin-aws

sender-sqs/src/main/java/zipkin/reporter/sqs/SQSSender.java, sender-sqs/src/test/java/zipkin/reporter/sqs/SQSSenderTest.java
AsyncReporter is the only thing that should be buffering.
Fixes #13
=> Undoes double-buffering in SQS

README.md, autoconfigure/collector-sqs/pom.xml, autoconfigure/collector-sqs/src/main/java/zipkin/autoconfigure/collector/sqs/ZipkinSQSCollectorAutoConfiguration.java, autoconfigure/collector-sqs/src/main/java/zipkin/autoconfigure/collector/sqs/ZipkinSQSCollectorProperties.java, autoconfigure/collector-sqs/src/main/resources/META-INF/spring.factories, autoconfigure/collector-sqs/src/test/java/zipkin/autoconfigure/collector/sqs/ZipkinSQSCollectorAutoConfigurationTest.java, build-support/go-offline.sh, build-support/pom-no-crossmodule-dependencies.xsl, circle.yml, collector-sqs/src/main/java/zipkin/collector/sqs/SQSCollector.java, collector-sqs/src/main/java/zipkin/collector/sqs/SQSSpanProcessor.java
This is work in progress to get PR builds working and also tackle work started by @abesto in the following branch https://github.com/openzipkin/zipkin-aws/tree/circleci
At this point I mostly want to get PR builds working correctly.
=> Fixes CI builds, enables PR builds and sets the path for CI releases.

autoconfigure/collector-sqs/README.md, autoconfigure/collector-sqs/pom.xml, autoconfigure/collector-sqs/src/main/resources/zipkin-server-sqs.yml, collector-sqs/README.md, pom.xml
This follows the config model adopted by the Azure project.
/cc @adriancole @devinsba @aliostad
=> Add module property config file

pom.xml, sender-kinesis/README.md, sender-kinesis/pom.xml, sender-kinesis/src/main/java/zipkin/reporter/kinesis/KinesisSender.java, sender-kinesis/src/test/java/zipkin/reporter/kinesis/KinesisSenderTest.java, sender-kinesis/src/test/resources/log4j2.properties
Not a huge user of autovalue so I pretty much copied the impl from `sender-sqs`. Please comment if there are issues. IntelliJ doesn't like it but it compiles, so..
Closes #16
=> Sender for kinesis

collector-kinesis/src/main/java/zipkin/collector/kinesis/KinesisSpanProcessor.java, collector-kinesis/src/test/java/zipkin/collector/kinesis/KinesisSpanProcessorTest.java
Will add tests to catch this in the future
=> Missunderstood the way the collector api worked.

README.md, autoconfigure/collector-kinesis/README.md, autoconfigure/collector-sqs/README.md, aws-junit/src/main/java/zipkin/junit/aws/AmazonSQSRule.java, collector-kinesis/README.md, collector-kinesis/src/main/java/zipkin/collector/kinesis/KinesisCollector.java, collector-sqs/README.md, collector-sqs/src/main/java/zipkin/collector/sqs/SQSSpanProcessor.java, collector-sqs/src/test/java/zipkin/collector/sqs/SQSCollectorTest.java, pom.xml, sender-kinesis/README.md, sender-kinesis/src/test/java/zipkin/reporter/kinesis/KinesisSenderTest.java, sender-sqs/README.md, sender-sqs/src/main/java/zipkin/reporter/sqs/SQSSender.java, sender-sqs/src/test/java/zipkin/reporter/sqs/SQSSenderTest.java
This shows examples of how to use AWS cli tools to send data in json.
=> Adds json encoding instructions for Kinesis and SQS

autoconfigure/collector-kinesis/src/main/java/zipkin/autoconfigure/collector/kinesis/package-info.java, autoconfigure/collector-sqs/src/main/java/zipkin/autoconfigure/collector/sqs/package-info.java, autoconfigure/sparkstreaming-stream-kinesis/src/main/java/zipkin/sparkstreaming/autoconfigure/stream/kinesis/package-info.java, aws-junit/src/main/java/zipkin/junit/aws/AmazonSQSRule.java, aws-junit/src/main/java/zipkin/junit/aws/package-info.java, collector-kinesis/src/main/java/zipkin/collector/kinesis/KinesisCollector.java, collector-kinesis/src/main/java/zipkin/collector/kinesis/package-info.java, collector-sqs/pom.xml, collector-sqs/src/main/java/zipkin/collector/sqs/SQSCollector.java, collector-sqs/src/main/java/zipkin/collector/sqs/SQSSpanProcessor.java, collector-sqs/src/main/java/zipkin/collector/sqs/package-info.java, pom.xml, sender-kinesis/pom.xml, sender-kinesis/src/main/java/zipkin/reporter/kinesis/KinesisSender.java, sender-kinesis/src/main/java/zipkin/reporter/kinesis/package-info.java, sender-sqs/pom.xml, sender-sqs/src/main/java/zipkin/reporter/sqs/SQSSender.java, sender-sqs/src/main/java/zipkin/reporter/sqs/package-info.java, sparkstreaming-stream-kinesis/src/main/java/zipkin/sparkstreaming/stream/kinesis/KinesisStreamFactory.java, sparkstreaming-stream-kinesis/src/main/java/zipkin/sparkstreaming/stream/kinesis/package-info.java
We'll soon start supporting zipkin v2. This begins the decoupling from
v1 internals.
=> Avoids zipkin internal classes and shades where impossible

sparkstreaming-stream-kinesis/src/main/java/zipkin/sparkstreaming/stream/kinesis/KinesisStreamFactory.java
Actually attempting to use this now and am squashing bugs that I find
=> Kinesis Streaming bugfixes

aws-junit/pom.xml, circle.yml, collector-sqs/pom.xml, collector-sqs/src/main/java/zipkin/collector/sqs/SQSCollector.java, collector-sqs/src/main/java/zipkin/collector/sqs/SQSSpanProcessor.java, collector-sqs/src/test/java/zipkin/collector/sqs/SQSCollectorTest.java, pom.xml
=> Updates build to java 9

autoconfigure/collector-kinesis/pom.xml, autoconfigure/collector-sqs/pom.xml, autoconfigure/pom.xml, autoconfigure/sparkstreaming-stream-kinesis/pom.xml, autoconfigure/storage-xray/pom.xml, aws-junit/pom.xml, collector-kinesis/pom.xml, collector-sqs/pom.xml, reporter-xray-udp/pom.xml, sender-kinesis/pom.xml, sender-sqs/pom.xml, sparkstreaming-stream-kinesis/pom.xml, storage-xray-udp/pom.xml
- required version bumps to do a release in the new year
=> New year POM version bump

autoconfigure/collector-kinesis/pom.xml, autoconfigure/collector-sqs/pom.xml, autoconfigure/storage-xray/pom.xml
Changing the build layout as per the Zipkin-Layout-Factory
=> Layout changes for the collector and storage using zipkin layout factory

brave-instrumentation/aws-java-sdk-core/pom.xml, brave-propagation-aws/README.md, brave-propagation-aws/pom.xml, brave-propagation-aws/src/main/java/brave/propagation/aws/AWSPropagation.java, brave-propagation-aws/src/test/java/brave/propagation/aws/AWSPropagationTest.java, pom.xml
Fixes https://github.com/openzipkin/brave/issues/712
=> Adds brave-propagation-aws

storage-xray-udp/src/main/java/zipkin2/storage/xray_udp/UDPMessageEncoder.java, storage-xray-udp/src/test/java/zipkin2/storage/xray_udp/UDPMessageEncoderTest.java
=> Don't write X-Ray type=subsegment unless parentId exists

autoconfigure/storage-elasticsearch-aws/src/main/java/zipkin/autoconfigure/storage/elasticsearch/aws/ElasticsearchDomainEndpoint.java, autoconfigure/storage-elasticsearch-aws/src/test/java/zipkin/autoconfigure/storage/elasticsearch/aws/ElasticsearchDomainEndpointTest.java
=> Supports VPC endpoints in elasticsearch

README.md
Found some issues in the README, minor edits with no side effects. Improves readability plus fixes broken links.
=> Minor typo and fix missing links in README

brave-instrumentation/aws-java-sdk-core/README.md, brave-instrumentation/aws-java-sdk-core/src/main/java/brave/instrumentation/aws/TracingRequestHandler.java, brave-instrumentation/aws-java-sdk-core/src/test/java/brave/instrumentation/aws/AwsClientTracingTest.java
=> Backport changes that were learned in V2 impl

brave-instrumentation/aws-java-sdk-core/pom.xml, brave-instrumentation/aws-java-sdk-core/src/main/java/brave/instrumentation/aws/AwsClientTracing.java, brave-instrumentation/aws-java-sdk-core/src/test/java/brave/instrumentation/aws/AwsClientTracingTest.java
=> Fix #121 and add a test

.dockerignore, docker/Dockerfile, docker/README.md, pom.xml
This is the zipkin-aws equivalent of https://github.com/openzipkin/zipkin/pull/2790. That PR has to be merged and an image built before this one.
=> Add a Dockerfile that can build master.

module/storage-elasticsearch-aws/src/main/java/zipkin/module/storage/elasticsearch/aws/ElasticsearchDomainEndpoint.java, module/storage-elasticsearch-aws/src/main/java/zipkin/module/storage/elasticsearch/aws/ZipkinElasticsearchAwsStorageModule.java, module/storage-elasticsearch-aws/src/test/java/zipkin/module/storage/elasticsearch/aws/ZipkinElasticsearchAwsStorageModuleTest.java, pom.xml
Verified unit tests pass with local SNAPSHOT. Have not verified against a real cluster.
=> Upgrade to Zipkin 2.20

reporter-xray-udp/src/main/java/zipkin2/reporter/xray_udp/XRayUDPReporter.java, reporter-xray-udp/src/test/java/zipkin2/reporter/xray_udp/XRayUDPReporterTest.java, storage-xray-udp/src/main/java/zipkin2/storage/xray_udp/UDPMessageEncoder.java, storage-xray-udp/src/test/java/zipkin2/storage/xray_udp/UDPMessageEncoderTest.java
The X-Ray SDKs report this, for example here
https://github.com/aws/aws-xray-sdk-java/blob/4528f395b10894ac2e1ac366976fe5ee9753eb57/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/AWSXRayRecorder.java#L156
It will be nice to record for Zipkin too :)
=> Add aws.xray.sdk field when encoding

.travis.yml, aws-junit/pom.xml, brave-instrumentation/aws-java-sdk-core/src/test/java/brave/instrumentation/aws/ITTracingRequestHandler.java, brave-instrumentation/aws-java-sdk-v2-core/src/test/java/brave/instrumentation/awsv2/ITTracingExecutionInterceptor.java, collector-kinesis/pom.xml, docker/Dockerfile, docker/Dockerfile.release, docker/README.md, module/storage-elasticsearch-aws/pom.xml, module/storage-elasticsearch-aws/src/main/java/zipkin/module/storage/elasticsearch/aws/AWSSignatureVersion4.java, pom.xml, storage-xray-udp/pom.xml
@vchittar this is probably what was breaking you. the versions just drifted
@anuraaga I've not setup locally my aws stuff.. do you mind doing a quick check on the test docker image of some service maybe SQS?
=> Bumps versions to latest

pom.xml
Updating to 5.13.4 to fix CVE-2021-44228
=> Fixing CVE-2021-44228

brave/propagation-aws/src/main/java/brave/propagation/aws/AWSPropagation.java, docker/Dockerfile, pom.xml
See https://github.com/openzipkin/brave/pull/1396 about Propagation and Brave 6.0
=> deps: updates to latest zipkin versions

.github/workflows/create_release.yml
=> ci: fixes comment on why JDK 17
