openzipkin/zipkin-aws

README.md, aws-junit/pom.xml, aws-junit/src/main/java/zipkin/junit/aws/AmazonSqsRule.java, collector-sqs/pom.xml, collector-sqs/src/main/java/zipkin/collector/sqs/AwsSqsCollector.java, collector-sqs/src/main/java/zipkin/collector/sqs/AwsSqsSpanProcessor.java, collector-sqs/src/test/java/zipkin/collector/sqs/AwsSqsCollectorTest.java, pom.xml, sender-sqs/src/main/java/zipkin/reporter/sqs/AwsBufferedSqsSender.java, sender-sqs/src/test/java/zipkin/reporter/sqs/AwsBufferedSqsSenderTest.java
An alternative Zipkin Span Collector implementation that leverages the AmazonSqsAsync callback API to chain SQS reads.
This implementation also allows a list of queue URLs to pull messages from multiple sources.
Further this takes advantage of the thread pool provided by the Amazon client as well as prefetching capabilities of the buffered client.
=> Fixes #1: SQS Span Collector

.settings.xml, build-support/publish-snapshot.sh, build-support/publish-stable.sh, build-support/trigger-publish.sh, circle.yml
This pulls in release scripts and CircleCI deployment config started by @abesto here https://github.com/openzipkin/zipkin-aws/tree/circleci
I've gone ahead and added ENV vars in CircleCI for my accounts.  I believe my accounts have the necessary permissions though there might be some debugging post merge.
=> Fixes #4: CI release configuration setup

autoconfigure/collector-sqs/pom.xml, autoconfigure/collector-sqs/src/main/java/zipkin/autoconfigure/collector/sqs/ZipkinSQSCollectorAutoConfiguration.java, autoconfigure/collector-sqs/src/test/java/zipkin/autoconfigure/collector/sqs/ZipkinSQSCollectorAutoConfigurationTest.java, autoconfigure/pom.xml, aws-junit/pom.xml, collector-sqs/pom.xml, pom.xml, sender-sqs/pom.xml
This changes config like `queueUrl` to `queue-url` and also updates the POM files with the correct snapshot version.  The snapshot version should have been done last release so that needs some investigation.
=> Fixes #24: use kebab case names for sqs auto config

README.md, autoconfigure/collector-sqs/pom.xml, autoconfigure/collector-sqs/src/main/java/zipkin/autoconfigure/collector/sqs/ZipkinSQSCollectorAutoConfiguration.java, autoconfigure/collector-sqs/src/main/java/zipkin/autoconfigure/collector/sqs/ZipkinSQSCollectorProperties.java, autoconfigure/collector-sqs/src/main/java/zipkin/autoconfigure/collector/sqs/ZipkinSQSCredentialsAutoConfiguration.java, autoconfigure/collector-sqs/src/main/resources/META-INF/spring.factories, autoconfigure/collector-sqs/src/test/java/zipkin/autoconfigure/collector/sqs/ZipkinSQSCollectorAutoConfigurationTest.java, collector-sqs/src/main/java/zipkin/collector/sqs/SQSCollector.java, collector-sqs/src/main/java/zipkin/collector/sqs/SQSSpanProcessor.java
Ran into a problem recently where the AWS SQS async callbacks were not being called when a queue was empty.  The net result is that the consumers stop consuming and require a server restart to kick them off again. After debugging this for a while I scrapped the async handler and resorted to using the synchronous API.
This PR also adds the ability to assume roles in AWS using the STS APIs.   All configuration changes for assume role authentication only effect the auto configuration library in a backwards compatible way.
/cc @devinsba @adriancole @bijnagte
=> Resolve async SQS issue when queue is empty

autoconfigure/collector-sqs/pom.xml, pom.xml
Copied module build config from here: https://github.com/openzipkin/zipkin/issues/1219.  Besides building things and reviewing the contents of the module JAR I haven't actually tested it any further.  Once the snapshots are deployed I can setup a Docker build as described in the ticket and test it out end to end.
=> Add server build, module build and bump upstream versions

circle.yml
Exceptions are not assertions, so materialize as errors. Errors don't
cause the integration-test phase to fail, while it will for verify.
=> Makes maven fail on error during integration tests

aws-junit/src/main/java/zipkin/junit/aws/AmazonSQSRule.java, collector-kinesis/src/main/java/zipkin/collector/kinesis/KinesisSpanProcessor.java, collector-sqs/src/main/java/zipkin/collector/sqs/SQSSpanProcessor.java, pom.xml, sender-kinesis/src/main/java/zipkin/reporter/kinesis/KinesisSender.java, sender-kinesis/src/test/java/zipkin/reporter/kinesis/KinesisSenderTest.java, sender-sqs/src/main/java/zipkin/reporter/sqs/SQSSender.java, sender-sqs/src/test/java/zipkin/reporter/sqs/SQSSenderTest.java
Before the AWS transports only supported thrift encoding. This adds json
support, which will notably be used for zipkin2 format.
This uses the recently released detecting decoder to support the new
Span2 format defined in https://github.com/openzipkin/zipkin/issues/1499
=> Adds support for json encoding, notably zipkin2 format

autoconfigure/collector-kinesis/pom.xml, autoconfigure/pom.xml, autoconfigure/sparkstreaming-stream-kinesis/pom.xml, autoconfigure/storage-xray/README.md, autoconfigure/storage-xray/pom.xml, autoconfigure/storage-xray/src/main/java/zipkin/autoconfigure/storage/xray/ZipkinXRayStorageAutoConfiguration.java, autoconfigure/storage-xray/src/main/java/zipkin/autoconfigure/storage/xray/ZipkinXRayStorageProperties.java, autoconfigure/storage-xray/src/main/resources/META-INF/spring.factories, autoconfigure/storage-xray/src/main/resources/zipkin-server-xray.yml, autoconfigure/storage-xray/src/test/java/zipkin2/storage/xray/ZipkinXRayStorageAutoConfigurationTest.java, collector-kinesis/pom.xml, collector-sqs/pom.xml, pom.xml, reporter-xray-udp/README.md, reporter-xray-udp/pom.xml, reporter-xray-udp/src/main/java/zipkin2/reporter/xray_udp/XRayUDPReporter.java, reporter-xray-udp/src/test/java/zipkin2/reporter/xray_udp/XRayUDPReporterTest.java, sender-kinesis/pom.xml, sender-sqs/pom.xml, sparkstreaming-stream-kinesis/pom.xml, storage-xray-udp/README.md, storage-xray-udp/pom.xml, storage-xray-udp/src/main/java/zipkin2/storage/xray_udp/BaseCall.java, storage-xray-udp/src/main/java/zipkin2/storage/xray_udp/UDPMessageEncoder.java, storage-xray-udp/src/main/java/zipkin2/storage/xray_udp/XRayUDPStorage.java, storage-xray-udp/src/test/java/zipkin2/storage/xray_udp/XRayUDPStorageTest.java
from https://github.com/openzipkin/brave/pull/510
This adds `XRayUDPReporter` which defaults to localhost:2000 or
AWS_XRAY_DAEMON_ADDRESS. This can be used in applications directly or
integrated with a zipkin-server where `STORAGE_TYPE=xray`
Note: this is experimental and makes assumptions about trace ID format:
See openzipkin/b3-propagation#6
=> Working XRayUDPReporter and STORAGE_TYPE xray

autoconfigure/collector-kinesis/src/main/resources/zipkin-server-kinesis.yml, sender-kinesis/README.md, sender-sqs/README.md
Extra space in the config breaks the yaml file and the kinesis collector doesn't start.
=> Removes extra space in the config, corrects doc

.mvn/wrapper/maven-wrapper.properties, autoconfigure/collector-kinesis/README.md, autoconfigure/collector-sqs/README.md, autoconfigure/pom.xml, autoconfigure/storage-elasticsearch-aws/src/main/resources/zipkin-server-elasticsearch-aws.yml, autoconfigure/storage-xray/README.md, pom.xml, storage-xray-udp/pom.xml
Recently, bean overriding is disabled by default. This affected aws
elasticsearch.
=> Uses latest layout factory and fixes a little drift

brave-propagation-aws/src/main/java/brave/propagation/aws/AWSPropagation.java, brave-propagation-aws/src/main/java/brave/propagation/aws/HexCodec.java, pom.xml
We accidentally dependended on an internal type without shading it. This
moves the two methods needed here.
Fixes #118
=> Updates to latest brave and avoids internal type

brave-instrumentation/aws-java-sdk-sqs/README.md, brave-instrumentation/aws-java-sdk-sqs/pom.xml, brave-instrumentation/aws-java-sdk-sqs/src/main/java/brave/instrumentation/aws/sqs/SendMessageTracingRequestHandler.java, brave-instrumentation/aws-java-sdk-sqs/src/main/java/brave/instrumentation/aws/sqs/SqsMessageTracing.java, brave-instrumentation/aws-java-sdk-sqs/src/test/java/brave/instrumentation/aws/sqs/SendMessageTracingRequestHandlerTest.java, brave-instrumentation/pom.xml
This is an implementation of SQS message propagation injection using the `RequestHandler2` methods in order to avoid client wrapping. Still needs an integration test but I wanted to get eyes on it.
This is modeled after the Brave Rabbit instrumentation and the work in `smartthings-brave`
=> SQS Message Propagation Injection

storage-xray-udp/src/main/java/zipkin2/storage/xray_udp/UDPMessageEncoder.java, storage-xray-udp/src/test/java/zipkin2/storage/xray_udp/UDPMessageEncoderTest.java
This PR implements support for the [EC2 section](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-aws) of the AWS segment in the X-Ray span metadata.  
As a result, X-Ray is able to regognise the tag as a special tag instead of having it as an annotation.
=> Implement support for aws ec2 segment in X-Ray UDP

autoconfigure/storage-elasticsearch-aws/src/main/java/zipkin/autoconfigure/storage/elasticsearch/aws/ElasticsearchDomainEndpoint.java
Health checks can only see the direct message of the throwable. When we
catch and re-wrap exceptions, we have to be careful not to throw away
the only thing that tells us what's wrong.
Ex before we hid the actual exception by guessing what the problem was.
Now, we can at least see what it is.
```bash
$ curl -s localhost:9411/health
{"status":"DOWN","zipkin":{"status":"DOWN","details":{"ElasticsearchStorage{initialEndpoints=aws://ap-southeast-1/zipkin-5, index=zipkin}":{"status":"DOWN","details":{"error":"java.lang.RuntimeException: couldn't lookup AWS ES domain endpoint: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY …
```
=> Makes the health check less useless especially in docker

docker/Dockerfile.release, docker/hooks/build
Not actually verified since it assumes the repo was migrated to the new module structure but here's the draft for now.
=> Add release Dockerfile for zipkin-aws.

pom.xml, reporter-xray-udp/pom.xml, reporter-xray-udp/src/test/java/zipkin2/reporter/xray_udp/XRayUDPReporterTest.java, reporter-xray-udp/src/test/java/zipkin2/storage/xray_udp/InternalStorageAccess.java, storage-xray-udp/pom.xml, storage-xray-udp/src/test/java/zipkin2/storage/xray_udp/XRayUDPStorageTest.java
I was randomly looking at the xray storage and want to convert to using Netty to likely improve performance a lot. But that would require benchmarking and reasoning about whether adding a dependency on Netty is OK (I guess so since other storage like elasticsearch has it).
In the meantime, it shouldn't require reasoning to use Netty for tests, which would help in the event we make a change to the storage implementation.
=> Add tests for XrayUDPStorage / Reporter.

module/storage-elasticsearch-aws/src/main/java/zipkin/module/storage/elasticsearch/aws/AWSSignatureVersion4.java, module/storage-elasticsearch-aws/src/main/java/zipkin/module/storage/elasticsearch/aws/ElasticsearchDomainEndpoint.java
Every other release of Armeria seems to have different behavior with regards to authority header /cc @trustin
Fixes #152
=> Remove port from authority header since we remove it when signing.

.github/workflows/docker-tests.yml, .github/workflows/docker/docker-compose.test.yml, .travis.yml, RELEASE.md, docker/build_image, travis/publish.sh
We've long since gotten to the bottom of this. Rather than always skipping the
license plugin in CI, causing a poor experience for people who have local builds
fail over it, this re-enables after underscoring the CI config needed to make it
work.
After this change, pull requests won't be green unless the headers are correct.
=> Re-enables license plugin

.dockerignore, build-bin/maven/maven_build, build-bin/maven/maven_build_or_unjar, build-bin/maven/maven_release, build-bin/maven/maven_unjar
When there was no prior build, this would have not worked
```bash
build-bin/docker/docker_build openzipkin/zipkin-aws:test
```
=> Fixes on-demand build in docker

brave/propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java, brave/propagation-aws/src/main/java/brave/propagation/aws/AWSInjector.java, brave/propagation-aws/src/main/java/brave/propagation/aws/AWSPropagation.java, brave/propagation-aws/src/test/java/brave/propagation/aws/AWSPropagationTest.java
Before, the reference to AWS custom fields wasn't final, so we can't
guarantee they would be readable at inject.
=> Fixes concurrency bug where another thread might not see custom fields

docker/Dockerfile, pom.xml
This PR upgrades Zipkin to the latest version, which solves the Log4j vulnerability. It also upgrades the log4j version used for the tests
=> Upgrade Zipkin and Log4j

aws-junit/pom.xml, brave/instrumentation-aws-java-sdk-core/pom.xml, brave/instrumentation-aws-java-sdk-sqs/pom.xml, brave/instrumentation-aws-java-sdk-v2-core/pom.xml, brave/propagation-aws/pom.xml, brave/propagation-aws/src/main/java/brave/propagation/aws/AWSInjector.java, brave/propagation-aws/src/test/java/brave/propagation/aws/AWSInjectorTest.java, collector/kinesis/pom.xml, collector/sqs/pom.xml, module/pom.xml, reporter/reporter-xray-udp/pom.xml, reporter/sender-awssdk-sqs/pom.xml, reporter/sender-kinesis/pom.xml, reporter/sender-sqs/pom.xml, storage/xray-udp/pom.xml
This bug was introduced in 0.23.2 by #186 and reported in #188.
The introduced tests now pass and should help avoid regression in this area.
=> Fixes #188, NPE when AwsInjector injects TracingContext without AmznTraceId extra

aws-junit/pom.xml, brave/instrumentation-aws-java-sdk-core/pom.xml, brave/instrumentation-aws-java-sdk-sqs/pom.xml, brave/instrumentation-aws-java-sdk-v2-core/pom.xml, brave/propagation-aws/pom.xml, collector/kinesis/pom.xml, collector/sqs/pom.xml, module/pom.xml, pom.xml, reporter/reporter-xray-udp/pom.xml, reporter/sender-awssdk-sqs/pom.xml, reporter/sender-kinesis/pom.xml, reporter/sender-sqs/pom.xml, storage/xray-udp/pom.xml
Seems that in the last release the version didn't turn back into `-SNAPSHOT`.
=> fix(build): set versions to proper snapshot

brave/propagation-aws/src/main/java/brave/propagation/aws/AWSExtractor.java, brave/propagation-aws/src/test/java/brave/propagation/aws/AWSPropagationTest.java
In this **PR** we want to propose a possible solution for [this issue](https://github.com/openzipkin/zipkin-aws/issues/201).
- In the first commit, the introduced test fails with the provided input: `Root=1-1373cbb-77f4b48ed7ff3eebbd62b5e01;Parent=1a4e96536a3ff131;Sampled=0` because it has a timestamp with 7 characters instead of 8. 
- In the second commit a possible solution is provided and the introduced test won't fail anymore.
We understood that the problem was that `traceIdHigh` and `traceId` variables were not reset when an unexpected condition is encountered during the parsing of the traced id. This behaviour is fixed in these lines: 
- [127](https://github.com/openzipkin/zipkin-aws/pull/203/files#diff-4cae479ac35f48f8eee3577fce4babc8d51a1e7c9b98f464b0c58c0cd803428bR127)
- …
=> refs #201: java.lang.IllegalStateException: Missing: traceId with AWS propagation type within AWSExtractor 

brave/propagation-aws/src/main/java/brave/propagation/aws/AWSPropagation.java, pom.xml
Note after we release, we should bump major when updating to zipkin-reporter 3.0.1
=> Prepares for release by updating to Brave 5.18

aws-junit/pom.xml, brave/instrumentation-aws-java-sdk-core/pom.xml, brave/instrumentation-aws-java-sdk-core/src/test/java/brave/instrumentation/aws/ITTracingRequestHandler.java, brave/instrumentation-aws-java-sdk-sqs/pom.xml, brave/instrumentation-aws-java-sdk-v2-core/pom.xml, brave/instrumentation-aws-java-sdk-v2-core/src/main/java/brave/instrumentation/awsv2/AwsSdkTracing.java, brave/instrumentation-aws-java-sdk-v2-core/src/main/java/brave/instrumentation/awsv2/TracingExecutionInterceptor.java, brave/instrumentation-aws-java-sdk-v2-core/src/test/java/brave/instrumentation/awsv2/ITTracingExecutionInterceptor.java, brave/propagation-aws/pom.xml, brave/propagation-aws/src/main/java/brave/propagation/aws/AWSPropagation.java, collector/kinesis/pom.xml, collector/sqs/pom.xml, module/pom.xml, pom.xml, reporter/reporter-xray-udp/pom.xml, reporter/sender-awssdk-sqs/pom.xml, reporter/sender-awssdk-sqs/src/main/java/zipkin2/reporter/awssdk/sqs/AbstractSender.java, reporter/sender-awssdk-sqs/src/main/java/zipkin2/reporter/awssdk/sqs/SQSAsyncSender.java, reporter/sender-awssdk-sqs/src/main/java/zipkin2/reporter/awssdk/sqs/SQSSender.java, reporter/sender-awssdk-sqs/src/test/java/zipkin2/reporter/awssdk/sqs/SQSAsyncSenderTest.java, reporter/sender-awssdk-sqs/src/test/java/zipkin2/reporter/awssdk/sqs/SQSSenderTest.java, reporter/sender-kinesis/pom.xml, reporter/sender-kinesis/src/main/java/zipkin2/reporter/kinesis/KinesisSender.java, reporter/sender-kinesis/src/test/java/zipkin2/reporter/kinesis/KinesisSenderTest.java, reporter/sender-sqs/pom.xml, reporter/sender-sqs/src/main/java/zipkin2/reporter/sqs/SQSSender.java, reporter/sender-sqs/src/test/java/zipkin2/reporter/sqs/SQSSenderTest.java, storage/xray-udp/pom.xml
Brave no longer has dependencies on zipkin types. To fully remove this dependency requires Zipkin Reporter 3 which repackages a few base types.
Call sites don't require changes, except dependency alignment. However, this sets to the next major version as it is a change.
=> deps: updates to Brave 6 and Zipkin Reporter 3

build-bin/docker/docker_test_image, pom.xml
=> Routine dependency updates
